import dayjs from "dayjs";

// TODO(vxern): This is hard-coded.
export default [{
  term: "jak",
  created_at: dayjs(),
}, {
  term: "widzã",
  created_at: dayjs(),
}, {
  term: "mōm",
  created_at: dayjs(),
}, {
  term: "ôbryncznik",
  created_at: dayjs(),
}, {
  term: "kōń",
  created_at: dayjs(),
}, {
  term: "śmiã",
  created_at: dayjs(),
}, {
  term: "przŏć",
  created_at: dayjs(),
}, {
  term: "ôstać",
  created_at: dayjs(),
}, {
  term: "udŏwać",
  created_at: dayjs(),
}, {
  term: "trzimiã",
  created_at: dayjs(),
}, {
  term: "erb",
  created_at: dayjs(),
}, {
  term: "erbowizna",
  created_at: dayjs(),
}, {
  term: "erbować",
  created_at: dayjs(),
}, {
  term: "raub",
  created_at: dayjs(),
}, {
  term: "chałupa",
  created_at: dayjs(),
}, {
  term: "dziywczym",
  created_at: dayjs(),
}, {
  term: "chcym",
  created_at: dayjs(),
}, {
  term: "jak",
  created_at: dayjs(),
}, {
  term: "widzã",
  created_at: dayjs(),
}, {
  term: "mōm",
  created_at: dayjs(),
}, {
  term: "ôbryncznik",
  created_at: dayjs(),
}, {
  term: "kōń",
  created_at: dayjs(),
}, {
  term: "śmiã",
  created_at: dayjs(),
}, {
  term: "przŏć",
  created_at: dayjs(),
}, {
  term: "ôstać",
  created_at: dayjs(),
}, {
  term: "udŏwać",
  created_at: dayjs(),
}, {
  term: "trzimiã",
  created_at: dayjs(),
}, {
  term: "erb",
  created_at: dayjs(),
}, {
  term: "erbowizna",
  created_at: dayjs(),
}, {
  term: "erbować",
  created_at: dayjs(),
}, {
  term: "raub",
  created_at: dayjs(),
}, {
  term: "chałupa",
  created_at: dayjs(),
}, {
  term: "dziywczym",
  created_at: dayjs(),
}, {
  term: "chcym",
  created_at: dayjs(),
}, {
  term: "jak",
  created_at: dayjs(),
}, {
  term: "widzã",
  created_at: dayjs(),
}, {
  term: "mōm",
  created_at: dayjs(),
}, {
  term: "ôbryncznik",
  created_at: dayjs(),
}, {
  term: "kōń",
  created_at: dayjs(),
}, {
  term: "śmiã",
  created_at: dayjs(),
}, {
  term: "przŏć",
  created_at: dayjs(),
}, {
  term: "ôstać",
  created_at: dayjs(),
}, {
  term: "udŏwać",
  created_at: dayjs(),
}, {
  term: "trzimiã",
  created_at: dayjs(),
}, {
  term: "erb",
  created_at: dayjs(),
}, {
  term: "erbowizna",
  created_at: dayjs(),
}, {
  term: "erbować",
  created_at: dayjs(),
}, {
  term: "raub",
  created_at: dayjs(),
}, {
  term: "chałupa",
  created_at: dayjs(),
}, {
  term: "dziywczym",
  created_at: dayjs(),
}, {
  term: "chcym",
  created_at: dayjs(),
}];