// Dykcjōnŏrze sōm idyntyfikowane podle familyjnego miana ôd autora.
// - kulik
// - syniawa
// - wencel
//
// Eźli je dwōch autorōw, miana sōm spŏjane po pōmocy dodatnij cechy (+).
// - neblik+orliński
// - mayer+rospond
// - czajkowscy+klukowscy
//
// Eźli niy ma jednego autora, jak u przikładu Wikcjōnŏrza, stŏwiŏ sie ôdnośnik ku zajcie.
// - en.wiktionary.org
//
export default Object.freeze({
  "kulik": {
    name: "SileSłownik",
    link: "https://silling.org/slownik",
    authors: ["Grzegorz Kulik"],
    licence: "CC BY-NC-SA 4.0",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
      total: 25340,
    },
  },
  "en.wiktionary.org": {
    name: "Wiktionary",
    link: "https://en.wiktionary.org",
    authors: "community",
    licence: "CC BY-SA 4.0",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
      total: 2227,
    },
  },
  "neblik+orliński": {
    name: "Dykcjōnorz",
    link: "https://dykcjonorz.eu",
    authors: ["Stanisław Neblik", "Wojciech Orliński"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "syniawa": {
    name: "Dykcjůnorz polsko-ślůnski",
    // TODO(vxern): Link?
    link: null,
    authors: ["Mirosław Syniawa"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "wencel": {
    name: "Dykcjůnôrz ślų̊sko-polski",
    link: "https://www.math.uni.wroc.pl/~wencel/sil/slownik_sp.pdf",
    authors: ["Aleksandra Wencel"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "kosmała/DPŚ": {
    name: "Dykcjōnôrz polsko-ślonskiy",
    link: "https://sbc.org.pl/dlibra/publication/648390",
    authors: ["Eugeniusz Kosmała"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "kosmała/DŚP": {
    name: "Dykcjōnôrz ślonsko-polski",
    link: "https://sbc.org.pl/dlibra/publication/648393",
    authors: ["Eugeniusz Kosmała"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "lerch-wójcik": {
    name: "Słowniczek wyrazów śląskich",
    link: "https://bonclok.pl/slowniczek-wyrazow-slaskich.html",
    authors: ["Anna Lerch-Wójcik"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  // TODO(vxern): What's this guy's real name?
  "fazi": {
    name: "Słownik śl𝑜nski",
    link: "https://www.slownikslaski.pl",
    authors: [],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "markowski": {
    name: "Słownik",
    link: "https://www.antryj.pl/category/slownik/",
    authors: ["Zbigniew Markowski"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "dygacz/słownik": {
    name: "Słownik gwarowy",
    link: "https://www.sbc.org.pl/dlibra/publication/880766/edition/802420",
    authors: ["Adolf Dygacz"],
    licence: "public",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
      // TODO(vxern): Should be right around this number, but this needs double-checking.
      total: 93,
    },
  },
  "dygacz/wyrazy": {
    name: "Słownik wyrazów gwarowych i technicznych",
    link: "https://www.sbc.org.pl/dlibra/publication/861664/edition/788851",
    authors: ["Adolf Dygacz"],
    licence: "public",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
      // TODO(vxern): Should be right around this number, but this needs double-checking.
      total: 290,
    },
  },
  "przywara": {
    name: "Narzecza śląskie",
    link: "https://sbc.org.pl/dlibra/publication/68791/edition/64871",
    authors: ["Michał Przywara"],
    licence: "public",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
      // TODO(vxern): It's at least 8,000, not sure how many exactly.
      total: 8000,
    },
  },
  "lazik": {
    name: "Kleines phraseologisches Wörterbuch der oberschlesischen Sprache im Bezirk Oppeln und Umgebung",
    link: "http://www.dr-lazik.de/",
    authors: ["Wolfgang Lazik"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "parczewska": {
    name: "Przyczynki do słownika gwary śląskiej",
    link: "https://silling.org/slownik/Aneks:Parczewska_-_Przyczynki_do_s%C5%82ownika_gwary_%C5%9Bl%C4%85skiej",
    authors: ["Melania Parczewska"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "nitsch": {
    name: "Dialekty polskie Śląska",
    link: "https://sbc.org.pl/dlibra/publication/600216/edition/564609",
    authors: ["Kazimierz Nitsch"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "olesch": {
    name: "Der Wortschatz der polnischen Mundart von Sankt Annaberg",
    link: "https://sbc.org.pl/dlibra/publication/958232",
    authors: ["Reinhold Olesch"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "wencel:rojśliny": {
    name: "Rojśliny po ślų̊sku",
    link: "https://www.math.uni.wroc.pl/~wencel/sil/rojsliny.pdf",
    authors: ["Aleksandra Wencel"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  // TODO(vxern): There are a lot of these Zarania, what to do about it?
  "zaranie:1/1929": {
    name: "Zaranie Śląskie nr 1/1929",
    // TODO(vxern): Add the original link.
    link: "https://silling.org/slownik/Aneks:S%C5%82ownik_-_Zaranie_%C5%9Al%C4%85skie_nr_1/1929",
    authors: ["Zaranie Śląskie"],
    licence: "public",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
    },
  },
  // TODO(vxern): Who made this? Is this even accessible anymore?
  "zestawienie.gatunków": {
    name: "Zestawienie gatunków roślin w ogrodach przydomowych na terenie śląska i ziemi kieleckiej",
    link: "https://instytutkorfantego.pl/wp-content/uploads/2020/12/ZESTAWIENIE-GATUNK%C3%93W-RO%C5%9ALIN-ROSN%C4%84CYCH-W-OGR%C3%93DKACH-PRZYDOMOWYCH.pdf",
    // TODO(vxern): Authors?
    authors: [],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "wencel:grziby": {
    name: "Grziby po ślų̊sku",
    link: "https://www.math.uni.wroc.pl/~wencel/sil/grziby.pdf",
    authors: ["Aleksandra Wencel"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "gładysz": {
    name: "Zdobnictwo metalowe na Śląsku",
    link: "https://pbc.gda.pl/dlibra/publication/1165/edition/8684",
    authors: ["Mieczysław Gładysz"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "euro-met.pl/techniczny": {
    name: "Śląski Słownik Techniczny i Narzędzi",
    link: "https://euro-met.pl/informator/slaski-slownik/item/slaski-slownik-narzedzi",
    authors: ["euro-met.pl"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "euro-met.pl/zawody": {
    name: "Śląskie zawody i zakłady pracy",
    link: "https://euro-met.pl/informator/slaski-slownik/item/narzedzia-wg-kategorii",
    authors: ["euro-met.pl"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "kallus": {
    name: "Słownik Górnoślōnskij Gŏdki",
    link: "https://lubimyczytac.pl/ksiazka/4439064/slownik-g-rnosl-nskij-g-dki",
    authors: ["Bogdan Kallus"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "słaboń": {
    name: "Słownik gwar śląskich",
    link: "https://sbc.org.pl/dlibra/publication/edition/912987",
    authors: ["Manfred Słaboń"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "wyderka": {
    name: "Słownik gwar śląskich",
    link: "https://instytutslaski.pl/slownik-gwar-slaskich/",
    authors: ["Bogusław Wyderka", "Małgorzata Iżykowska", "Beata Jahołkowska", "Krzysztof Kleszcz", "Lidia Przymuszała", "Danuta Lech-Kirstein", "Anna Jedynak", "Marzena Muszyńska", "Kamila Nowak", "Agata Haas"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "roczniok/zbornik": {
    name: "Zbornik polsko-ślůnski",
    link: null,
    authors: ["Andrzej Roczniok"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "rubin-lorek/minisłownik": {
    name: "Wyrazy staropolskie w dialekcie śląskim — Śląski minisłownik etymologiczny",
    link: "https://ruj.uj.edu.pl/entities/publication/54f2c875-75b3-442f-8825-be4ed6d7d143",
    authors: ["Mirela Rubin-Lorek"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "cząstka-szymon+ludwig+synowiec/słownik": {
    name: "Mały słownik gwary Górnego Śląska",
    link: "https://katalog.ijp.pan.pl/index.php?KatID=0&typ=record&001=KR%20IJPPAN14000155",
    authors: ["Bożena Cząstka-Szymon", "Jerzy Ludwig", "Helena Synowiec"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "pluta/dzierżysławice": {
    name: "Słownictwo Dzierżysławic w powiecie prudnickim",
    link: "https://books.google.co.uk/books/about/S%C5%82ownictwo_Dzier%C5%BCys%C5%82awic_w_powiecie_p.html?id=Gf0CAAAAMAAJ",
    authors: ["Feliks Pluta"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "mayer+rospond/przeszłość": {
    name: "Z badań nad przeszłością dialektu śląskiego",
    link: "https://www.czestochowa-wom.sowa.pl/index.php?KatID=0&typ=record&001=CST%20WOM16058887",
    authors: ["Józef Mayer", "Stanisław Rospond"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "zaręba/AJŚ": {
    name: "Atlas językowy Śląska",
    link: "https://rcin.org.pl/dlibra/publication/43411",
    authors: ["Alfred Zaręba"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "cinciała": {
    name: "Słownik dialektyczny Księstwa Cieszyńskiego",
    link: "https://integro.bs.katowice.pl/32102035247/cinciala-andrzej/slownik-dyalektyczny-ksiestwa-cieszynskiego-z-dodatkiem-przyslowiow-i-frazeologii",
    authors: ["Andrzej Cinciała"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "bąk+rospond": {
    name: "Słownik gwarowy Śląska",
    link: "https://www.bu.umk.pl/wymiana/index.php?10503,slownik-gwarowy-slaska-stanislaw-bak-stanislaw-rospond.-opole-instytut-slaski-1962.-26-2014-140.",
    authors: ["Stanisław Bąk", "Stanisław Rospond"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "podgórscy": {
    name: "Słownik gwar śląskich",
    link: "https://ksiegarniainternetowa.co.uk/pl/slownik_gwar_slaskich-9788376491769",
    authors: ["Adam Podgórski", "Barbara Podgórska"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  // TODO(vxern): Who wrote this?
  "nieznany": {
    name: "Nieznany śląski słownik gwarowy",
    // TODO(vxern): Link?
    link: null,
    // TODO(vxern): Author?
    authors: [],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "furgalińska": {
    name: "Ślónsko Godka",
    link: "https://www.chorzow-mbp.sowa.pl/index.php?typ=record&001=CHORZ%20M10059732",
    authors: ["Joanna Furgalińska"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "czajkowscy+klukowscy": {
    name: "Słownik gwary śląskiej",
    link: "https://m6122.lib.mol.pl/description/13122308/slownik-gwary-slaskiej-13122308",
    authors: ["Andrzej Czajkowski", "Ilona Czajkowska", "Andrzej Klukowski", "Dorota Klukowska"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "szołtysek/ilustrowany": {
    name: "Ilustrowany słownik gwary śląskiej",
    link: "https://integro.bs.katowice.pl/ici/recorddetail?id=0033507219298",
    authors: ["Marek Szołtysek"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "szczeponek/czasowniki": {
    name: "Czasowniki ślõski",
    link: "https://opac.r-sl.pl/953601047942/szczeponek-andrzej/czasowniki-slaskie?internalNav=1&bibFilter=95",
    authors: ["Andrzej Szczeponek"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "dyrda/godka": {
    name: "Rýchtig Gryfno Godka",
    link: "https://lubimyczytac.pl/ksiazka/4031580/rychtig-gryfno-godka",
    authors: ["Dariusz Dyrda"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  // TODO(vxern:): Who wrote this really?
  "lepiarczyk": {
    name: "Internetowy Słownik Języka Śląskiego",
    link: "https://web.archive.org/web/20210610050834/http://www.republikasilesia.com/RS/slownik/index.htm",
    // TODO(vxern:): Who actually wrote this?
    authors: ["Krzysztof Lepiarczyk"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "szołtysek": {
    name: "Słownik",
    link: "https://web.archive.org/web/20080907174824/http://www.slaskie-abc.com.pl/slownik.txt",
    authors: ["Marek Szołtysek"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "hellfeier": {
    name: "Słownik śląsko-polski",
    link: "https://geudka.eu/slownik/",
    authors: ["Robert Hellfeier"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "wiora": {
    name: "Słownik śląsko-polski",
    link: "https://jozef.wiora.pl/szl/slownik.pdf",
    authors: ["Józef Wiora"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "wacławczyk": {
    name: "Słownik gwary strzeleckiej",
    link: "http://moreantiqua.com/slownik-gwary-strzeleckiej-2/",
    authors: ["Norbert Wacławczyk"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "zaręba/siołkowice": {
    name: "Słownik starych Siołkowic w powiecie opolskim",
    link: "https://www.opole-wbp.sowa.pl/index.php?KatID=0&typ=record&001=Op2006059002",
    authors: ["Alfred Zaręba"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  // TODO(vxern:): Who wrote this?
  "segeth": {
    name: "Słownik gwary w Zborowskiem",
    link: "https://www.zborowskie.info/articles/gwara-slaska",
    authors: ["Witold Segeth"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "koczwarty/wyrażenia": {
    name: "Kilka wyrażeń ludowych z Małych Kończyc koło Zebrzydowic na Śląsku",
    // TODO(vxern:): Original link?
    link: "https://silling.org/slownik/Aneks:Koczwara_-_Kilka_wyra%C5%BCe%C5%84_ludowych_z_Ma%C5%82ych_Ko%C5%84czyc_ko%C5%82o_Zebrzydowic_na_%C5%9Al%C4%85sku",
    authors: ["Jan Koczwarty"],
    licence: "public",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
      // TODO(vxern:): Needs checking against the original.
      total: 198,
    },
  },
  "klocek/wyrażenia": {
    name: "2675 wyrażeń gwarowych, używanych w potocznej mowie przez rdzenną ludność wsi Zebrzydowice k/ Cieszyna",
    link: "https://sbc.org.pl/dlibra/publication/820194/edition/754268",
    authors: ["Karol Klocek"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "olesch/sprachmischung": {
    name: "Sprachmischung in Oberschlesien",
    link: "https://sbc.org.pl/dlibra/publication/381621/edition/359601",
    authors: ["Reinhold Olesch"],
    licence: "public",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
    },
  },
  "olesch/dialekte": {
    name: "Die slavischen Dialekte Oberschlesiens",
    link: "https://sbc.org.pl/dlibra/publication/960723/edition/870378",
    authors: ["Reinhold Olesch"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "steuer/sulkowski": {
    name: "Dialekt sulkowski",
    link: "https://books.google.co.uk/books/about/Dialekt_Sulkowski.html?id=ub_aXQ0f4BAC",
    authors: ["Feliks Steuer"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "steuer/baborów": {
    name: "Narzecze baborowskie",
    link: "https://sbc.org.pl/dlibra/publication/447886/edition/420224",
    authors: ["Feliks Steuer"],
    licence: "public",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
    },
  },
  "bystroń/przyczynek": {
    name: "Przyczynek do dialektologji polskiej (z narzecza Lachów szląskich)",
    // TODO(vxern): Original link.
    link: "https://silling.org/slownik/Aneks:Bystro%C5%84_-_Przyczynek_do_dialektologii_polskiej_(z_narzecza_Lach%C3%B3w_szl%C4%85skich)",
    authors: ["Jan Bystroń"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "biały/słowniczek": {
    name: "Słowniczek gwary wsi pszczyńskiej",
    // TODO(vxern): Link?
    link: null,
    authors: ["Anna Biały"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "cieśla/słownik": {
    name: "Słownik gwary śląskiej - okolice Suszca i Pawłowic w ziemi pszczyńskiej",
    // TODO(vxern): Link?
    link: null,
    authors: ["Marian Cieśla"],
    licence: "proprietary",
    access: "limited",
    redistributable: false,
  },
  "klus/slovník": {
    name: "Slovník po naszimu",
    link: "http://www.blaf.cz/index.php?body=slovnik",
    authors: ["Jan Klus"],
    licence: "granted",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
      // TODO(vxern): Somewhere around this mark.
      total: 4630,
    },
  },
  "bogocz/słownictwo": {
    name: "Zachodniocieszyńskie słownictwo gwarowe - próba ujęcia",
    link: "https://bibliotekanauki.pl/articles/3150548.pdf",
    authors: ["Irena Bogocz"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "nowrotek/słownik": {
    name: "Słownik gwarowy czechowicki",
    link: "https://nowrotek.hoste.pl/files/slownikstela.pdf",
    authors: ["Zdzisław Nowrotek"],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  // TODO(vxern): Who wrote this?
  "unknown/slovník": {
    name: "Slovník z oblasti Domaslavic",
    link: "https://www.ponasimu.cz/slovnik-po-nasimu-cesky/a/",
    // TODO(vxern): Who wrote this?
    authors: [],
    licence: "proprietary",
    access: "open",
    redistributable: false,
  },
  "działas/zbiór": {
    name: "Zbiór wyrazów szląsko-polskich",
    link: "https://jbc.bj.uj.edu.pl/dlibra/publication/338687/edition/323579",
    authors: ["Baltazar Działas"],
    licence: "public",
    access: "open",
    redistributable: true,
    progress: {
      imported: 0,
    },
  },
});